# Generated by Django 4.0.2 on 2022-02-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_computadora_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marca', verbose_name='nombre'),
        ),
    ]
