# Generated by Django 4.0.2 on 2022-02-11 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_computadora_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='marca',
            field=models.ForeignKey(db_column='nombre', on_delete=django.db.models.deletion.CASCADE, to='api.marca'),
        ),
    ]
